# Generated by Django 3.2.25 on 2024-09-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='recipes/images/No-Food-Image.png', upload_to='recipe/images'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(default='recipes/images/No-Food-Image.png', max_length=255),
            preserve_default=False,
        ),
    ]
