# Generated by Django 3.2.25 on 2024-09-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20240930_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
    ]
